[build]
  publish = "/"
  command = ""

# Redirect non-existent pages to 404
[[redirects]]
  from = "/services/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/blog/*/blog/"
  to = "/404.html"
  status = 404

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 