[build]
  publish = "/"
  command = ""

# Redirect non-existent pages to 404
[[redirects]]
  from = "/services/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/blog/*/blog/"
  to = "/404.html"
  status = 404

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[redirects]]
  from = "/blog/modern-haircut-trends-2024/"
  to = "/blog/modern-haircut-trends-2025/"
  status = 301

[[redirects]]
  from = "/blog/best-hair-products-men-2024/"
  to = "/blog/best-hair-products-men-2025/"
  status = 301 